### ISSUE TITLE
create transformer for combining SVG files 

### ISSUE THREAD

**Issue by tylerlee** [caseywebdev/cogs#6]
like https://github.com/FWeinb/grunt-svgstore but in cogs.

**Comment by caseywebdev** [comment]
How would you use a concatenated SVG file with an `<img>` tag?

**Comment by caseywebdev** [comment]
Looks like `<svg>` is the only way to use them?

**Comment by tylerlee** [comment]
Yeah it is, SVG tag only, so you have to have a backup for IE . 

Let's talk about after my SVG presentation but I think doing this and creating an SVG-sprite with fragment identifiers is going to be the best way to include SVGs.

**Comment by jpowell** [comment]
@tylerlee When is said presentation?

**Comment by tylerlee** [comment]
https://orgsync.com/74471/events/995764/occurrences/2196070
